fixtures/groovy/admin/createSite.groovy, src/utils/Utils.ts
https://jira.jahia.org/browse/TECH-1108
=> TECH-1108: Add createSite method and update groovy script associated

fixtures/graphql/jcr/mutation/addVanityUrl.graphql, fixtures/graphql/jcr/mutation/deleteNodeProperty.graphql, fixtures/graphql/jcr/mutation/removeVanityUrl.graphql, fixtures/graphql/jcr/query/getNodeByPath.graphql, fixtures/graphql/jcr/query/getVanityUrls.graphql, src/utils/Utils.ts
https://jira.jahia.org/browse/PROJECT-XXX
After the test was done, I had some interesting functions to share
=> TECH-1200 Improve jahia-cypress utils

src/support/fixture.ts
https://jira.jahia.org/browse/TECH-1200
Small fix
=> TECH-1200 Increase timeout to avoid failures

package.json
https://jira.jahia.org/browse/TECH-1200
Change module version
=> TECH-1200 change module version

package.json
https://jira.jahia.org/browse/TECH-1200
Change version to 3.6.0
=> TECH-1200 change version again

fixtures/graphql/jcr/mutation/moveNode.graphql, package.json, src/utils/JCRHelper.ts
https://jira.jahia.org/browse/TECH-1201
Add util function to move a Node with graphql
=> TECH-1201 add moveNode util function

fixtures/graphql/jcr/query/getNodeByPath.graphql, package.json, src/utils/JCRHelper.ts
https://jira.jahia.org/browse/TECH-1128
=> TECH-1128: Allow to pass worskpace to getNodeByPath

fixtures/graphql/jcr/query/getNodeTypes.graphql, src/utils/JCRHelper.ts
https://jira.jahia.org/browse/BACKLOG-21202
=> BACKLOG-21202 : add getNodeTypes function

ci.build.sh
https://jira.jahia.org/browse/BACKLOG-21402
Add support for test submodules; Copy all jars instead of just top-level
=> BACKLOG-21402: Add support for test submodules

fixtures/graphql/jcr/mutation/unpublishNode.graphql, fixtures/groovy/admin/abortWorkflows.groovy, package.json, src/utils/PublicationAndWorkflowHelper.ts
add unpublication and workflow abortion functions
=> add unpublication and workflow abortion functions

fixtures/graphql/jcr/mutation/revokeRoles.graphql, package.json, src/utils/UsersHelper.ts
https://jira.jahia.org/browse/BACKLOG-21278
=> BACKLOG-21278 : add function to revoke role on a node

src/support/fixture.ts
https://jira.jahia.org/browse/DMF-6194
=> DMF-6194 : increase timeout to avoid error when reading files

package.json
=> DMF-6188: Bumped version to 3.17.5

src/support/provisioning/index.ts, src/support/provisioning/uninstallBundle.ts
https://jira.jahia.org/browse/QA-14229
https://jira.jahia.org/browse/TECH-1550
The following are included in this PR
I have considered the following implications of my change:
=> QA-14229 TECH-1550 SUP-363 Add new uninstall function

env.Dockerfile, package.json
https://jira.jahia.org/browse/TECH-1635
- Small fixes to make the image generation work properly.
-
=> TECH-1635 Fixes

.yarnrc.yml, ci.build.sh, env.Dockerfile, package.json
https://jira.jahia.org/browse/TECH-1635
Now that we have a proper system to use specific versions of this project in different repositories, we add support for multiple versions of Yarn back to this project.
=> TECH-1635 Second take

fixtures/graphql/sam/healthStatus.graphql, package.json, src/utils/SAMHelper.ts, src/utils/index.ts
https://jira.jahia.org/browse/TECH-1844
=> TECH-1844: Added a method to wait until SAM returns green

package.json
=> QA-14990 : upgrade version

package.json, src/support/apollo/apolloClient.ts
https://jira.jahia.org/browse/TECH-1867
=> TECH-1867: Fixed an issue with providing auth values without URL

env.run.sh
https://jira.jahia.org/browse/BACKLOG-23326
```
024-10-23T10:21:21.1955351Z [36mcypress             |[0m 
2024-10-23T10:21:21.1965946Z [36mcypress             |[0m [0m  ([4m[1mRun Starting[22m[24m)[0m
2024-10-23T10:21:21.1967420Z [36mcypress             |[0m 
2024-10-23T10:21:21.2172824Z [36mcypress             |[0m [90m  ┌[39m[90m─[39m[90m─[39m[90m─[39m[90m─[39m[90m─[39m[90m─[39m[90m─[39m[90m─[39m[90m─[39m[90m─[39m[90m─[39m[90m─[39m[90m─[39m[90m─[39m[90m─[39m[90m─[39m[90m─[39m[90m─[39m[90m─[39m[90m─[39m[90m─[39m[90m─[39m[90m─[39m[90m─[39m[90m─[39m[90m─[39m[90m─[39m[90m─[39m[90m─[39m[90m─[39m[90m─[39m[90m─[39m[90m─[39m[90m─[39m[90m─[39m[90m─[39m[90m─[39m[90m─[39m[90m─[39m[90m─[39m[90m─[39m[90 …
```
=> BACKLOG-23326: Remove garbage characters in logs

fixtures/graphql/jcr/query/getStartedModulesVersion.graphql, package.json, src/utils/JahiaPlatformHelper.ts
https://jira.jahia.org/browse/DMF-6379
=> DMF-6379: add function to get modules version

fixtures/graphql/jcr/mutation/addMixins.graphql, src/utils/JCRHelper.ts
https://jira.jahia.org/browse/DMF-6406
=> DMF-6406: add addMixins functions

src/page-object/moonstone/menu.ts
Selector causing issues on certain values; needs to be enclosed with double quotes
=> fix: Fix attribute selector value
